name: scanwedge
description: A Flutter plugin to communicate with the Zebra Datawedge
version: 1.0.1
homepage: https://github.com/Rokke/scanwedge

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: no.talgoe.scanwedge.scanwedge
        pluginClass: ScanwedgePlugin